= Examples

By combining these molecules, you can achieve even more privacy and
throughput gain.


== The Hierarchical Throughput Molecule

In this model, a single layer of hub and spoke does not supply enough
throughput to the system. Perhaps one branch in a bank is in the dense
city center and processes triple the transactions of the other branches.
This branch can then split into their own hierarchy and aggregate their
data upwards, being their own spoke and hub model.

This allows them to gain another potential order of magnitude more
throughput without affecting the other branches.


#### Spokes as Control Chains

In this architecture each company has a chain that holds the entirety of
their data. They do not wish to share, so no other parties can see that
data. A directory chain (the hub) contains hashes of company chains
participating in consortium which maintains data integrity and trust
system wide. All parties in this architecture participate in directory
chain. Hashes provide shared auditability and accountability throughout
network without sharing any trade data.

The companies do, however, wish to shared trade data with each other.
Therefore, the parties control trading chains run between them that
contain this trade data. The company chains control the trading chains
and send hashes to the directory to maintain data integrity of the
trades by proxy.

The blue chains, trading chains, were completely hidden from anyone
other than the involved parties. The green company chains are controlled
entirely by the companies in question. The red chain has hashes
periodically reported to it so that every party involved accountable for
data integrity of their individual chains.
