export default {
  HOME: '/',
  CONTACT: '/contact',
  DEVELOPERS: '/developers',
  DEVELOPERS_APP_DIRECTORY: '/developers/app-directory',
  DEVELOPERS_ARCHITECTURE: '/developers/architecture',
  DEVELOPERS_BEST_PRACTICES: '/developers/best-practices',
  DEVELOPERS_BLUEPRINTS: '/developers/app-blueprints',
  DEVELOPERS_BUILDING_INTERBIT_APPS: '/developers/building-interbit-apps',
  DEVELOPERS_EXAMPLES: '/developers/example-apps',
  DEVELOPERS_IDENTITY: '/developers/identity',
  DEVELOPERS_PLATFORM_FEATURES: '/developers/platform-features',
  DEVELOPERS_PROJECTS: '/developers/projects',
  DEVELOPERS_RESOURCES: '/developers/resources',
  DEVELOPERS_SUPPORT: '/developers/support',
  PLATFORM: '/platform',
  PLATFORM_INTERBIT_FOR_BUSINESS: '/platform/interbit-for-business',
  PLATFORM_ROADMAP: '/platform/roadmap',
  PRICING: '/pricing',
  POLICY_ACCEPTABLE_USE: '/policy/acceptable-use',
  POLICY_PRIVACY: '/policy/privacy',
  POLICY_TOS: '/policy/terms-of-use',
  POLICY_TRADEMARK: '/policy/trademark'
}
